print("Download the package and save it in the folder C:\\Users\\r_med\\Documents\\Software\\Python\\")
print("While in IntelliJ, open a Terminal window (a tab at the bottom of the screen)")
print("Notice that the prompt has the virtual environment (or venv) that you created (in my case python39)")
print("at the very beginning, right before the creation of the first Python Project, as well as a path:")
print("(python39) C:\\Users\\r_med\\IdeaProjects\\HelloFunctions>")
print("From the Terminal window, run the command:")
print("pip install [full path]\\package_name")
print("For example:")
print("pip install c:\\Users\\r_med\\Documents\\Software\\Python\\colorama_lpa-0.4.4b1.0-py2.py3-none-any.whl")

input("Press ENTER to continue")
print("\n"*10)

print("In addition to the Terminal window installation, you can use IntelliJ's GUI:")
print("From the Main Menu select File->Project Structure...")
print("From the pop-up window select SDK from the left pane, your venv (python39) from the middle pane, and")
print("the Packages tab from the right pane.")
print("Click + on the right pane to search for the package that you want to add/install and follow")
print("the instructions to install it.")

input("Press ENTER to continue")
print("\n"*10)

print("When running or testing a Python script from the Windows Command Prompt (cmd)")
print("You first need to activate the venv (virtual environment) where the Package was installed")
print("In my case, the venv is called python39")
print("You need to run the 'activate' command, which is located in the same directory as the venv.")
print("You can find the venv path easily: each time that you run a py script in IntelliJ, the first line")
print("shows the venv path. To activate the venv then, run the following from the cmd window:")
print("C:\\Users\\r_med\\venv\\python39\\Scripts\\activate")
print("You can now run the py script with the packages installed in the venv.")
print("After running the py script, don't forget to deactivate the venv:")
print("C:\\Users\\r_med\\venv\\python39\\Scripts\\deactivate")
